apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::385499079243:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NQ92VSUOMFXT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::385499079243:role/UdacityFlaskDeployCBKubectlRole
      username: build    
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-07T21:27:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1500"
  uid: 2ee5d522-fe11-4786-9856-36db1f218e46
